services:
  openplc:
    image: fdamador/openplc
    container_name: openplc_runtime
    ports:
      - "8080:8080"  # Web UI for OpenPLC
      - "502:502"    # Modbus/TCP port
    volumes:
      - ./plc_logic:/usr/src/app/plc_logic
    networks:
      - control_network

  scada_dashboard:
    build:
      context: .
      dockerfile: Dockerfile.scada
    container_name: scada_dashboard
    depends_on:
      - openplc
    ports:
      - "5001:5000"  # Web dashboard port (external:internal)
    volumes:
      - .:/usr/src/app
    networks:
      - control_network
    command: python web_dashboard.py
    
  scada_hmi:
    build:
      context: .
      dockerfile: Dockerfile.scada
    container_name: scada_hmi
    depends_on:
      - openplc
    volumes:
      - .:/usr/src/app
    networks:
      - control_network
    command: python physical_process.py

networks:
  control_network:
    driver: bridge