services:
  openplc:
    image: fdamador/openplc
    container_name: openplc_runtime
    ports:
      - "8080:8080"  # Web UI for OpenPLC
      - "502:502"    # Modbus/TCP port
    volumes:
      - ./plc_logic:/usr/src/app/plc_logic
    networks:
      - control_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  scada_dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: scada_dashboard
    container_name: scada_dashboard
    volumes:
      - /tmp:/shared_data
    ports:
      - "5001:5001"
    environment:
      - OPENPLC_HOST=openplc_runtime
      - OPENPLC_PORT=502
    # depends_on:
    #   openplc:
    #     condition: service_healthy
    networks:
      - control_network
    command: python web_dashboard.py
    
  scada_hmi:
    build:
      context: .
      dockerfile: Dockerfile.scada
    container_name: scada_hmi
    depends_on:
      - openplc
    volumes:
      - .:/usr/src/app
      - /tmp:/shared_data  # Share data between containers
    networks:
      - control_network
    command: python physical_process_enhanced.py
    environment:
      - PYTHONUNBUFFERED=1
    profiles:
      - console  # This service only starts when explicitly requested

networks:
  control_network:
    driver: bridge